ent_snowflakeAccelXMax: 3.0
ent_snowflakeAccelXMin: 1.0
ent_snowflakeSizeMax: 100
ent_snowflakeSizeMin: 30
ent_snowflakeSpeedX: 1.0
ent_snowflakeSpeedYMax: 12.0
ent_snowflakeSpeedYMin: 4.0
ent_snowflakesNumber: 20
r_fullscreenMode: true
r_fullscreenResolutionHeight: 1080
r_fullscreenResolutionWidth: 1920
r_windowResolutionHeight: 800
r_windowResolutionWidth: 1600
