ent_snowflakeAccelXMax: 3.0
ent_snowflakeAccelXMin: 1.0
ent_snowflakeSizeMax: 50
ent_snowflakeSizeMin: 25
ent_snowflakeSpeedX: 0.2
ent_snowflakeSpeedYMax: 2.0
ent_snowflakeSpeedYMin: 0.8
ent_snowflakesNumber: 18
r_fullscreenMode: false
r_fullscreenResolutionHeight: 1080
r_fullscreenResolutionWidth: 1920
r_windowResolutionHeight: 600
r_windowResolutionWidth: 800
